/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class jnilirc_JniRcxIr */

#ifndef _Included_jnilirc_JniRcxIr
#define _Included_jnilirc_JniRcxIr
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     jnilirc_JniRcxIr
 * Method:    open
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jnilirc_JniRcxIr_open
  (JNIEnv *, jobject, jstring);

/*
 * Class:     jnilirc_JniRcxIr
 * Method:    close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnilirc_JniRcxIr_close
  (JNIEnv *, jobject);

/*
 * Class:     jnilirc_JniRcxIr
 * Method:    send
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_jnilirc_JniRcxIr_send
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     jnilirc_JniRcxIr
 * Method:    write
 * Signature: ([BI)I
 */
JNIEXPORT jint JNICALL Java_jnilirc_JniRcxIr_write
  (JNIEnv *, jobject, jbyteArray, jint);

/*
 * Class:     jnilirc_JniRcxIr
 * Method:    read
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Java_jnilirc_JniRcxIr_read
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     jnilirc_JniRcxIr
 * Method:    test
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_jnilirc_JniRcxIr_test
  (JNIEnv *, jobject);

/*
 * Class:     jnilirc_JniRcxIr
 * Method:    intTest
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_jnilirc_JniRcxIr_intTest
  (JNIEnv *, jobject);

/*
 * Class:     jnilirc_JniRcxIr
 * Method:    message
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_jnilirc_JniRcxIr_message
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
