/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class lirc_Lirchandler */

#ifndef _Included_lirc_Lirchandler
#define _Included_lirc_Lirchandler
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     lirc_Lirchandler
 * Method:    rcx_1open
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lirc_Lirchandler_rcx_1open
  (JNIEnv *, jobject);

/*
 * Class:     lirc_Lirchandler
 * Method:    rcx_1close
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_lirc_Lirchandler_rcx_1close
  (JNIEnv *, jobject);

/*
 * Class:     lirc_Lirchandler
 * Method:    rcx_1send
 * Signature: (IIII)I
 */
JNIEXPORT jint JNICALL Java_lirc_Lirchandler_rcx_1send
  (JNIEnv *, jobject, jint, jint, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
